# Generated by Django 4.0.1 on 2022-01-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('forum', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
