# Generated by Django 4.0.1 on 2022-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_solution_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(),
        ),
    ]
