# Generated by Django 4.0.1 on 2022-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_social_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='short_intro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
